export const AuthLoginTypes = {
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT: "LOGOUT",
    ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
    ACCESS_TOKEN_REFRESHED: "ACCESS_TOKEN_REFRESHED"
}